<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>VaultUserCloudUpload</RootNamespace>
    <AssemblyName>VaultUserCloudUpload</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\x64\Debug\2026\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>Key.snk</AssemblyOriginatorKeyFile>
    <BaseOutputPath>C:\Users\Administrator\source\repos\Vault-Extension-Sample---UserCloudUpload\Vault.UserCloudUploadCore\bin\Debug\net8.0</BaseOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\2026\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\2026\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Autodesk.Connectivity.Explorer.Extensibility">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.Connectivity.Explorer.Extensibility.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Connectivity.Explorer.ExtensibilityTools">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.Connectivity.Explorer.ExtensibilityTools.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Connectivity.Extensibility.Framework">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.Connectivity.Extensibility.Framework.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Connectivity.IDServicesWrapper">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.Connectivity.IDServicesWrapper.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Connectivity.WebServices">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.Connectivity.WebServices.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Connectivity.WebServices.WCF">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.Connectivity.WebServices.WCF.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework.Forms">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.Forms.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework.Vault">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.Vault.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework.Vault.Forms">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.Vault.Forms.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Data.Desktop.v24.1">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\DevExpress.Data.Desktop.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Data.v24.1">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\DevExpress.Data.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Drawing.v24.1">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\DevExpress.Drawing.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Printing.v24.1.Core">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\DevExpress.Printing.v24.1.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Utils.v24.1">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\DevExpress.Utils.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraEditors.v24.1">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\DevExpress.XtraEditors.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraLayout.v24.1">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2026 SDK\bin\x64\core\DevExpress.XtraLayout.v24.1.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BrowserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="Autodesk Vault-2-Cloud -- Sample Application Case Study.pdf" />
    <None Include="Autodesk Vault-2-Cloud -- Sample Application Setup.pdf" />
    <None Update="VaultUserCloudUpload.vcet.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Vault.UserCloudUploadSettings.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Add_Generic_16.png" />
    <Content Include="Resources\AdminOptionsImage_16_dark.png" />
    <Content Include="Resources\AdminOptionsImage_16_light.ico" />
    <Content Include="Resources\AppMngr_16x16_dark.png" />
    <Content Include="Resources\AppMngr_32x32_dark.png" />
    <Content Include="Resources\autodesk-docs-small-badge-16.png" />
    <Content Include="Resources\autodesk-drive-small-badge-16.png" />
    <Content Include="Resources\autodesk-fusion-team-small-badge-16.png" />
    <Content Include="Resources\CheckIn_16_dark.png" />
    <Content Include="Resources\CheckIn_32_dark.png" />
    <Content Include="Resources\CheckOut_16_dark.png" />
    <Content Include="Resources\CheckOut_32_dark.png" />
    <Content Include="Resources\cmdPush_16_dark.png" />
    <Content Include="Resources\cmdPush_16_light.ico" />
    <Content Include="Resources\cmdPush_32_dark.png" />
    <Content Include="Resources\GlobalFolderView_16_dark.png" />
    <Content Include="Resources\GlobalFolderView_16_light.ico" />
    <Content Include="Resources\GlobalFolderView_32_dark.png" />
    <Content Include="Resources\Sites_16_dark.png" />
    <Content Include="Resources\Sites_16_light.ico" />
    <Content Include="Resources\Sites_32_dark.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\licenses.licx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1370.28" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.DirectoryServices" Version="9.0.1" />
  </ItemGroup>
</Project>